services:
  lambdamysql:
    container_name: lambdadatamysql
    image: mysql:8.0
    volumes:
      - lamda-db:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lambda
      MYSQL_DATABASE: lambda

volumes:
  lamda-db: {}
